config/routes.rb
Rails.application.routes.draw do

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end


  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  #get 'test/display'
  #get 'demo2/index'
  #simple route (system automatically creates simple route of a controller)
  #get 'demo/index'
  #get 'demo/hello'
  # get 'demo/learning_render'
  # get 'demo/external_url'
  # root 'demo#index'

  #root route
 
  


  #default route
  get ':controller(/:action(/:id))' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
    #because this class automaticattly calls users table which no longer exists.
    #it has been changed to admin_users
    #self.table_name="admin_users" _

    has_and_belongs_to_many :pages
    has_many :section_edits
    has_many :sections, :through => :section_edits


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
    
    belongs_to :subject, { :optional => false}
    has_many :sections
    has_and_belongs_to_many :admin_users 

    scope :visible, lambda{ where(:visible => true)}
    scope :invisible, lambda{ where(:invisible => false)}
    scope :sorted, lambda{ order("position ASC")}
    scope :newest_first, lambda{ order("created_at DESC")}
    scope :search, lambda{|query| where(["name LIKE ?","%#{query}%"])}
end

app/models/section.rb
class Section < ApplicationRecord

    belongs_to :page
    has_many :section_edits
    has_many :admin_users, :through => :section_edits

    scope :visible, lambda{ where(:visible => true)}
    scope :invisible, lambda{ where(:invisible => false)}
    scope :sorted, lambda{ order("position ASC")}
    scope :newest_first, lambda{ order("created_at DESC")}
    scope :search, lambda{|query| where(["name LIKE ?","%#{query}%"])}
    
end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord

    belongs_to :admin_user
    belongs_to :section

end

app/models/subject.rb
class Subject < ApplicationRecord

    has_many :pages

    scope :visible, lambda{ where(:visible => true)}
    scope :invisible, lambda{ where(:visible => false)}
    scope :sorted, lambda{ order("position ASC") }
    scope :newest_first, lambda{ order("created_at DESC")}
    scope :search, lambda{ |query| where(["name LIKE ?","%#{query}%"])}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demo1_controller.rb
class Demo1Controller < ApplicationController
  def index
  end
end

app/controllers/demo2_controller.rb
class Demo2Controller < ApplicationController
  def index
  end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false
  def index
    render('index')
  end

  def hello
    @array = [1,2,3,4,5]
    @id = params['id']
    @page = params['page']
    render('hello')
  end

  def learning_render
    #redirect_to(:controller => 'demo', :action => 'index')
    redirect_to(:action => 'index')
  end

  def external_url
    redirect_to("http://lynda.com") 
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'admin'
  def index
    @pages=Page.all
  end

  def show
    @page=Page.find(params[:id])
  end

  def new
    @page=Page.new(:name => "riva")
  end

  def create
    @page=Page.new(page_params)
    if @page.save
      flash[:notice]="Page Created Successfully"
      redirect_to(pages_path)
    else
      render('new')
    end
  end

  def edit
    @page=Page.find(params[:id])
  end

  def update
    @page=Page.find(params[:id])
    if @page.update_attributes(page_params)
      flash[:notice] = 'Page Updated Successfully'
      redirect_to(page_path(@page))
    else
      render('edit')
    end

  end

  def delete
    @page=Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Page '#{@page.name}' destroyed successfully"
    redirect_to(pages_path)
  end

  private
  
  def page_params
    params.require(:page).permit(:subject_id, :name, :position, :visible, :permalink)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  layout 'admin'
  def index
    @sections=Section.all
  end

  def show
    @section=Section.find(params[:id])
  end

  def new
    @section=Section.new
  end

  def create
    @section=Section.new(section_params)
    if @section.save
      flash[:notice]="Section Created Successfully"
      redirect_to(sections_path)
    else
      render('new')
    end
  end

  def edit
    @section=Section.find(params[:id])
  end

  def update
    @section=Section.find(params[:id])
    if @section.update_attributes(section_params)
      flash[:notice]='Section Updated Successfully'
      redirect_to(section_path(@section))
    else
      render('edit')
    end
  end

  def delete
    @section=Section.find(params[:id])

  end

  def destroy
    @section=Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section '#{@section.name}' destroyed successfully"
    redirect_to(sections_path)
  end


  private
  def section_params
    params.require(:section).permit(:page_id, :name, :position, :visible)
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  layout 'admin'
  def index
    @subjects = Subject.sorted
    

  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject=Subject.new(:name => "riva")
  end

  def create
    @subject=Subject.new(subject_params)
    if @subject.save
      flash[:notice]="Subject Created Successfully"
      redirect_to(subjects_path)
    else
      render('new')
    end
  end

  def edit
    @subject=Subject.find(params[:id])
  end

  def update
    @subject=Subject.find(params[:id])
    if @subject.update_attributes(subject_params)
      flash[:notice] = 'Subject updated successfully'
      redirect_to(subject_path(@subject))
    else
       render('edit')
    end
  end

  def delete
    @subject=Subject.find(params[:id])
  end

  def destroy
    @subject=Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.name}' destroyed successfully"
    redirect_to(subjects_path)
  end

  private
  def subject_params
    params.require(:subject).permit(:name, :position, :visible, :content_type, :content)
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  layout false
  def display
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_tag(boolean, options={})
    options[:true_text] ||=''
    options[:false_text] ||=''

    if boolean
      content_tag(:span, options[:true_text], :class => 'status true')
    else
      content_tag(:span, options[:false_text], :class => 'status false')
    end

  end
end

app/helpers/demo1_helper.rb
module Demo1Helper
end

app/helpers/demo2_helper.rb
module Demo2Helper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/demo/hello.html.erb
 <h1> hello world from  hello page </h1>

 <%= 1+1 %>


 <% var="learning templates on rails"  %><br>
 <%= "Hello I am #{var}" %>

 <%
 @array.each do |n| %>
   <%= n%>
 <% end 
 %>

 <%= link_to("hello",'/demo/index') %><br/>

 <%= link_to("hello",{:controller => 'demo', :action => 'index'}) %> <br/>

 ID=<%= @id %><br/>
 Page=<%= @page %><br/>
 Page1=<%= params['page'] %><br/>
 Page2=<%= params[:page] %><br/>
 Nextpage=<%= @page.to_i + 1 %>

app/views/demo/index.html.erb
<h1>Hello World from index!</h1>
<a href="/demo/hello">hello </a>
<br>

<%= link_to("hello page 2",{:controller => 'demo', :action => 'hello' }) %><br/>

<%= link_to("hello with parameters",{:action => 'hello', :page => 5, :id => 20}) %>
<br/>

app/views/demo1/index.html.erb
<h1>Demo1#index</h1>
<p>Find me in app/views/demo1/index.html.erb</p>

app/views/demo2/index.html.erb
<h1>Demo2#index</h1>
<p>Find me in app/views/demo2/index.html.erb</p>

app/views/sections/_form.html.erb
<table summary="Section form fields">
<tr>
  <th>Page ID</th>
  <td><%= f.text_field(:page_id) %></td>
</tr>
<tr>
  <th>Name</th>
  <td><%= f.text_field(:name) %></td>
</tr>
<tr>
  <th>Position</th>
  <td><%= f.text_field(:position) %></td>
</tr>
<tr>
  <th>Visible</th>
  <td><%= f.text_field(:visible) %></td>
</tr>
</table>

app/views/sections/delete.html.erb
<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="sections delete">
  <h2>Delete Section</h2>

  <%= form_for(@section, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this section?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>

  <% end %>
</div>

app/views/sections/edit.html.erb
<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="sections edit">
  <h2>Update Section</h2>

  <%= form_for(@section) do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Section") %>
    </div>

  <% end %>
</div>

app/views/sections/index.html.erb
<div class="sections index">
  <h2>Sections</h2>

  <%= link_to("Add New Section", new_section_path , :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th> * </th>
      <th>Page Id</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <% @sections.each do |section| %>
    <tr>
      
      <td><%= section.position %> </td>
      <td><%= section.page_id %> </td>
      <td><%= section.name %> </td>
      <td class="center"><%= status_tag(section.visible) %></td>
      <td class="center"><%= section.content_type %></td>
      <td class="actions">
      <!--can use "subjects/#{subject.id}" or "subject_path(subject) or {:controller => subjects, :action => show, :id => subject.id}"-->
        <%= link_to("Show", section_path(section), :class => 'action show') %>
        <%= link_to("Edit", edit_section_path(section), :class => 'action edit') %>
        <%= link_to("Delete", delete_section_path(section), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/sections/new.html.erb
<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="pages new">
  <h2>Create Section</h2>

  <%= form_for(@section) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>


    <div class="form-buttons">
      <%= f.submit("Create Section") %>
    </div>

  <% end %>


</div>

app/views/sections/show.html.erb
<%= link_to("<< Back to List", sections_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Section</h2>

  <table summary="Section detail view">
    <tr>
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @section.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
        <th>Content Type</th>
        <td><%= @section.content_type %></td>
      </tr>
      <tr>
        <th>Content</th>
        <td><%= @section.content %></td>
      </tr>
    <tr>
      <th>Created</th>
      <td><%= @section.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @section.updated_at %></td>
    </tr>
  </table>

</div>

app/views/subjects/_form.html.erb
<table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
</table>

app/views/subjects/delete.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Subject</h2>

  <%= form_for(@subject, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this subject?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f})%>


    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/index.html.erb
<% @page_title="AllSubject" %>

<div class="subjects index">
  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path , :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th> * </th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %> </td>
      <td><%= subject.name %> </td>
      <td class="center"><%= status_tag(subject.visible) %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
      <!--can use "subjects/#{subject.id}" or "subject_path(subject) or {:controller => subjects, :action => show, :id => subject.id}"-->
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f})%>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>


</div>

app/views/subjects/show.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>