config/routes.rb
Rails.application.routes.draw do

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end


  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  #get 'test/display'
  #get 'demo2/index'
  #simple route (system automatically creates simple route of a controller)
  #get 'demo/index'
  #get 'demo/hello'
  # get 'demo/learning_render'
  # get 'demo/external_url'
  # root 'demo#index'

  #root route
 
  


  #default route
  get ':controller(/:action(/:id))' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
    #because this class automaticattly calls users table which no longer exists.
    #it has been changed to admin_users
    #self.table_name="admin_users" _

    has_and_belongs_to_many :pages
    has_many :section_edits
    has_many :sections, :through => :section_edits


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
    
    belongs_to :subject, { :optional => false}
    has_many :sections
    has_and_belongs_to_many :admin_users 

    scope :visible, lambda{ where(:visible => true)}
    scope :invisible, lambda{ where(:invisible => false)}
    scope :sorted, lambda{ order("position ASC")}
    scope :newest_first, lambda{ order("created_at DESC")}
    scope :search, lambda{|query| where(["name LIKE ?","%#{query}%"])}
end

app/models/section.rb
class Section < ApplicationRecord

    belongs_to :page
    has_many :section_edits
    has_many :admin_users, :through => :section_edits

    scope :visible, lambda{ where(:visible => true)}
    scope :invisible, lambda{ where(:invisible => false)}
    scope :sorted, lambda{ order("position ASC")}
    scope :newest_first, lambda{ order("created_at DESC")}
    scope :search, lambda{|query| where(["name LIKE ?","%#{query}%"])}
    
end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord

    belongs_to :admin_user
    belongs_to :section

end

app/models/subject.rb
class Subject < ApplicationRecord

    has_many :pages

    scope :visible, lambda{ where(:visible => true)}
    scope :invisible, lambda{ where(:visible => false)}
    scope :sorted, lambda{ order("position ASC") }
    scope :newest_first, lambda{ order("created_at DESC")}
    scope :search, lambda{ |query| where(["name LIKE ?","%#{query}%"])}

end

app/controllers/demo1_controller.rb
class Demo1Controller < ApplicationController
  def index
  end
end

app/controllers/demo2_controller.rb
class Demo2Controller < ApplicationController
  def index
  end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false
  def index
    render('index')
  end

  def hello
    @array = [1,2,3,4,5]
    @id = params['id']
    @page = params['page']
    render('hello')
  end

  def learning_render
    #redirect_to(:controller => 'demo', :action => 'index')
    redirect_to(:action => 'index')
  end

  def external_url
    redirect_to("http://lynda.com") 
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'admin'
  def index
    @pages=Page.all
  end

  def show
    @page=Page.find(params[:id])
  end

  def new
    @page=Page.new(:name => "riva")
  end

  def create
    @page=Page.new(page_params)
    if @page.save
      flash[:notice]="Page Created Successfully"
      redirect_to(pages_path)
    else
      render('new')
    end
  end

  def edit
    @page=Page.find(params[:id])
  end

  def update
    @page=Page.find(params[:id])
    if @page.update_attributes(page_params)
      flash[:notice] = 'Page Updated Successfully'
      redirect_to(page_path(@page))
    else
      render('edit')
    end

  end

  def delete
    @page=Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Page '#{@page.name}' destroyed successfully"
    redirect_to(pages_path)
  end

  private
  
  def page_params
    params.require(:page).permit(:subject_id, :name, :position, :visible, :permalink)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  layout 'admin'
  def index
    @sections=Section.all
  end

  def show
    @section=Section.find(params[:id])
  end

  def new
    @section=Section.new
  end

  def create
    @section=Section.new(section_params)
    if @section.save
      flash[:notice]="Section Created Successfully"
      redirect_to(sections_path)
    else
      render('new')
    end
  end

  def edit
    @section=Section.find(params[:id])
  end

  def update
    @section=Section.find(params[:id])
    if @section.update_attributes(section_params)
      flash[:notice]='Section Updated Successfully'
      redirect_to(section_path(@section))
    else
      render('edit')
    end
  end

  def delete
    @section=Section.find(params[:id])

  end

  def destroy
    @section=Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section '#{@section.name}' destroyed successfully"
    redirect_to(sections_path)
  end


  private
  def section_params
    params.require(:section).permit(:page_id, :name, :position, :visible)
  end

end

app/controllers/test_controller.rb
class TestController < ApplicationController
  layout false
  def display
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_tag(boolean, options={})
    options[:true_text] ||=''
    options[:false_text] ||=''

    if boolean
      content_tag(:span, options[:true_text], :class => 'status true')
    else
      content_tag(:span, options[:false_text], :class => 'status false')
    end

  end
end

app/helpers/demo1_helper.rb
module Demo1Helper
end

app/helpers/demo2_helper.rb
module Demo2Helper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/admin.html.erb
<!DICTYPE html>
<html>
<head>
<title>Simple CMS: <%= @page_title || "Admin Area"%></title >
<style>
      span.status { display: block; width: 10px; height: 10px;
        margin: 0.25em auto; padding: 0; border: 1px solid #000000; }
      span.status.true  { background: green; color: green; }
      span.status.false { background: red; color: red; }
    </style>
</head>
    
<body>
<% if !flash[:notice].blank? %>
    <div class="notice">
        <%= flash[:notice] %>
    </div>
<% end %>
<!--before yield-->
<%=yield %>
<!--after yield-->
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<table summary="Page form fields">
        <tr>
        <th>Subject ID</th>
        <td><%= f.text_field(:subject_id) %></td>
      </tr>
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
</table>

app/views/pages/delete.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages delete">
  <h2>Delete Subject</h2>

  <%= form_for(@page, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this subject?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>

  <% end %>
</div>

app/views/pages/edit.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Page</h2>

  <%= form_for(@page) do |f| %>

  <%= render(:partial => form, :locals => {:f => f})%>  
    <div class="form-buttons">
      <%= f.submit("Update Page") %>
    </div>

  <% end %>
</div>

app/views/pages/index.html.erb
  <%= link_to("Add New Page", new_page_path , :class => 'action new') %>

  <table class="listing" summary="Page list">
    <tr class="header">
      <th> * </th>
      <th>Page</th>
      <th>Visible</th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.position %> </td>
      <td><%= page.name %> </td>
      <td class="center"><%= status_tag(page.visible)%></td>
      <td class="center"><%= page.sections.size %></td>
      <td class="actions">
      <!--can use "pages/#{page.id}" or "subject_path(subject) or {:controller => subjects, :action => show, :id => subject.id}"-->
        <%= link_to("Show", page_path(page), :class => 'action show') %>
        <%= link_to("Edit", edit_page_path(page), :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages new">
  <h2>Create Page</h2>

  <%= form_for(@page) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f})%>

    <div class="form-buttons">
      <%= f.submit("Create Page") %>
    </div>

  <% end %>


</div>

app/views/pages/show.html.erb
<% if !flash[:notice].blank? %>
    <div class="notice">
        <%= flash[:notice] %>
    </div>
<% end %>

<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages show">
  <h2>Show Page</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
    <tr>
        <th>Content Type</th>
        <td><%= f.text_field(:content_type) %></td>
      </tr>
      <tr>
        <th>Content</th>
        <td><%= f.text_field(:content) %></td>
      </tr>
  </table>

</div>